import type { JsonSchema, JsonType, SchemaRegistry } from "./schema.js";
import { reachableSchemas, refName } from "./schema.js";

/**
 * The contract's code generator.
 *
 * `openapi.yaml` is authored by hand; `src/types.ts` and `schemas/ws.json` are
 * not. Two hundred lines here beats a dependency whose output we would have to
 * read anyway — the same reasoning that keeps the Swift models hand-written and
 * pinned by fixtures instead of generated by a tool nobody in the repo owns.
 *
 * Everything in this module is pure: schemas in, source text out. The drift
 * gate in `tests/contract.test.ts` re-renders and compares, so a spec change
 * that was not regenerated fails `npm test` rather than reaching a squad.
 */

const HEADER = `/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Rendered from shared/openapi.yaml by shared/src/generate.ts.
 * Regenerate with \`npm run contract:generate\`; \`npm test\` fails if this
 * file has drifted from the spec.
 */

/** A successful response body. Every endpoint returns this or \`Err\`. */
export type Ok<T> = { readonly success: true; readonly data: T };

/** A failed response body. \`error.code\` is the contract; the status is advisory. */
export type Err = { readonly success: false; readonly error: ApiError };

/** The only two shapes a Syl response body can take. */
export type Envelope<T> = Ok<T> | Err;
`;

/** Render `src/types.ts` from the schema registry. */
export function renderTypes(registry: SchemaRegistry): string {
  const blocks = Object.entries(registry).map(([name, node]) => {
    const doc = docComment(node.description);
    return `${doc}export type ${name} = ${typeExpression(node)};\n`;
  });
  return `${HEADER}\n${blocks.join("\n")}`;
}

/**
 * Render `schemas/ws.json`: a self-contained JSON Schema 2020-12 bundle of the
 * WebSocket frames, carved out of the single registry by reachability so a
 * frame shape still has exactly one definition.
 */
export function renderWsJsonSchema(registry: SchemaRegistry, roots: readonly string[]): string {
  const names = reachableSchemas(registry, roots);
  const defs: Record<string, unknown> = {};
  for (const name of names) {
    const node = registry[name];
    if (node !== undefined) defs[name] = rewriteRefs(node);
  }
  const bundle = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://syl.invalid/schemas/ws.json",
    title: "Syl WebSocket frames",
    description:
      "GENERATED FILE — DO NOT EDIT. Rendered from shared/openapi.yaml. " +
      "Every frame on the socket is one of these. Note that `presence` carries no " +
      "`seq` and is never replayed; see shared/ws-protocol.md.",
    oneOf: roots.map((name) => ({ $ref: `#/$defs/${name}` })),
    $defs: defs,
  };
  return `${JSON.stringify(bundle, null, 2)}\n`;
}

/**
 * Render one schema node as a TypeScript type expression.
 *
 * `indent` is the leading whitespace of the line the expression starts on, so
 * nested objects close their braces in the right column. Three squads read
 * this output; a 400-character single line is not a contract anyone checks.
 */
export function typeExpression(node: JsonSchema, indent = ""): string {
  if (node.$ref !== undefined) return refName(node.$ref);

  if (node.allOf !== undefined && node.allOf.length > 0) {
    const parts = node.allOf.map((child) => typeExpression(child, indent));
    return parts.length === 1 ? (parts[0] as string) : parts.join(" & ");
  }

  if (node.oneOf !== undefined && node.oneOf.length > 0) {
    return node.oneOf.map((child) => typeExpression(child, indent)).join(" | ");
  }

  if (node.const !== undefined) return JSON.stringify(node.const);

  if (node.enum !== undefined) return node.enum.map((value) => JSON.stringify(value)).join(" | ");

  if (node.type === undefined) return "unknown";

  const types = Array.isArray(node.type) ? node.type : [node.type];
  const rendered = types.map((t) => scalarExpression(t, node, indent));
  return rendered.join(" | ");
}

function scalarExpression(type: JsonType, node: JsonSchema, indent: string): string {
  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "array":
      return node.items === undefined
        ? "unknown[]"
        : `${wrap(typeExpression(node.items, indent))}[]`;
    case "object":
      return objectExpression(node, indent);
  }
}

/** `A | B` needs parentheses before `[]`; `A` does not. */
function wrap(expression: string): string {
  return /[|&]/.test(expression) ? `(${expression})` : expression;
}

function objectExpression(node: JsonSchema, indent: string): string {
  const properties = Object.entries(node.properties ?? {});
  if (properties.length === 0) {
    if (node.additionalProperties === false) return "Record<string, never>";
    return "{ readonly [key: string]: unknown }";
  }
  const required = new Set(node.required ?? []);
  const inner = `${indent}  `;
  const members = properties.map(([key, child]) => {
    const optional = required.has(key) ? "" : "?";
    return `readonly ${propertyKey(key)}${optional}: ${typeExpression(child, inner)}`;
  });
  if (typeof node.additionalProperties === "object") {
    members.push(
      `readonly [key: string]: ${typeExpression(node.additionalProperties, inner)} | undefined`,
    );
  } else if (node.additionalProperties === true) {
    members.push("readonly [key: string]: unknown");
  }
  if (members.length < 2) return `{ ${members.join("; ")} }`;
  return `{\n${members.map((m) => `${inner}${m};`).join("\n")}\n${indent}}`;
}

/** `ttl_ms` is a bare identifier; anything odd gets quoted rather than breaking the file. */
function propertyKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function docComment(description: string | undefined): string {
  if (description === undefined || description.trim() === "") return "";
  const lines = description.trimEnd().split("\n");
  return `/**\n${lines.map((line) => ` * ${line}`.trimEnd()).join("\n")}\n */\n`;
}

/** Deep-copy a schema node, rewriting `#/components/schemas/X` to `#/$defs/X`. */
function rewriteRefs(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(rewriteRefs);
  if (value === null || typeof value !== "object") return value;
  const out: Record<string, unknown> = {};
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    out[key] = key === "$ref" && typeof child === "string" ? `#/$defs/${refName(child)}` : rewriteRefs(child);
  }
  return out;
}
